Repository Anamika1-cpu/Hacktoberfest2023-Web-Developers, pull requests merged in 2023-10, with the labels that each got.

#10 created todo list
  Todo List/index.html
  Todo List/script.js
  Todo List/style.css
Labels: hacktoberfest-accepted

#9 Create index.html
  Login Page using Firebase/index.html
Labels: hacktoberfest-accepted

#13 Add Tic-tac-toe game which was created html css js
  tic-tac-toe-vanilla-js/LICENSE
  tic-tac-toe-vanilla-js/css/main.css
  tic-tac-toe-vanilla-js/index.html
  tic-tac-toe-vanilla-js/js/Game.js
  tic-tac-toe-vanilla-js/js/GameView.js
  tic-tac-toe-vanilla-js/js/main.js
Labels: hacktoberfest, hacktoberfest-accepted

#15 Added Chrome Extension for Live cricket news
  Chrome Extension/index.html
  Chrome Extension/manifest.json
  Chrome Extension/script.js
  Chrome Extension/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#16 Added Color Picker
  ColorPicker/index.html
  ColorPicker/script.js
  ColorPicker/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#17 Added Random-GIF-Generator project
  Random-GIF-Genarator/.gitignore
  Random-GIF-Genarator/package-lock.json
  Random-GIF-Genarator/package.json
  Random-GIF-Genarator/random-gif-starter/.env
  Random-GIF-Genarator/random-gif-starter/.gitignore
  Random-GIF-Genarator/random-gif-starter/README.md
  Random-GIF-Genarator/random-gif-starter/package-lock.json
  Random-GIF-Genarator/random-gif-starter/package.json
  Random-GIF-Genarator/random-gif-starter/public/android-chrome-192x192.png
  Random-GIF-Genarator/random-gif-starter/public/android-chrome-512x512.png
  Random-GIF-Genarator/random-gif-starter/public/apple-touch-icon.png
  Random-GIF-Genarator/random-gif-starter/public/favicon-16x16.png
  Random-GIF-Genarator/random-gif-starter/public/favicon-32x32.png
  Random-GIF-Genarator/random-gif-starter/public/favicon.ico
  Random-GIF-Genarator/random-gif-starter/public/index.html
  Random-GIF-Genarator/random-gif-starter/public/robots.txt
  Random-GIF-Genarator/random-gif-starter/public/site.webmanifest
  Random-GIF-Genarator/random-gif-starter/src/App.jsx
  Random-GIF-Genarator/random-gif-starter/src/components/Random.js
  Random-GIF-Genarator/random-gif-starter/src/components/Spinner.js
  Random-GIF-Genarator/random-gif-starter/src/components/Tag.js
  Random-GIF-Genarator/random-gif-starter/src/hooks/useGif.js
  Random-GIF-Genarator/random-gif-starter/src/index.css
  Random-GIF-Genarator/random-gif-starter/src/index.js
  Random-GIF-Genarator/random-gif-starter/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added a Customised Linktree project.
  Linktree/images/avatar1.png
  Linktree/images/bg.png
  Linktree/images/icon.png
  Linktree/index.html
  Linktree/script.js
  Linktree/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#20 Added: Finance Webpage
  Finance Webpage/index.html
  Finance Webpage/index.js
  Finance Webpage/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#26 feat: improved the CSS of login page(#22)
  Login Page using Firebase/image/table1.jpg
  Login Page using Firebase/style.css
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added tic tac toe with an AI opponent
  tic-tac-toe-AI-opponent/LICENSE
  tic-tac-toe-AI-opponent/css/main.css
  tic-tac-toe-AI-opponent/index.html
  tic-tac-toe-AI-opponent/js/Game.js
  tic-tac-toe-AI-opponent/js/GameView.js
  tic-tac-toe-AI-opponent/js/main.js
Labels: hacktoberfest, hacktoberfest-accepted

#37 added Password Generator Website
  password generator/index.html
  password generator/script.js
  password generator/style.css
Labels: hacktoberfest-accepted

#36 added meme generator website
  Meme Generator/index.html
  Meme Generator/script.js
  Meme Generator/style.css
Labels: hacktoberfest-accepted

#33 "calculator added"
  .replit
  calculator/index.html
  calculator/style.css
  replit.nix
Labels: hacktoberfest-accepted

#29 made changes to layout of the webpage
  Finance Webpage/style.css
Labels: hacktoberfest-accepted

#30 Added Password-Generator Project
  passwordGenerator/.DS_Store
  passwordGenerator/assets/copy.svg
  passwordGenerator/assets/favicon.ico
  passwordGenerator/index.html
  passwordGenerator/script.js
  passwordGenerator/styles.css
Labels: hacktoberfest-accepted

#34 Added project language translator
  Language translator/lang.css
  Language translator/lang.html
  Language translator/lang.js
  Language translator/script.js
Labels: hacktoberfest-accepted

#39 added Image Slider Website
  Image Slider/index.html
  Image Slider/script.js
  Image Slider/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#42 React-calculator added
  React-Calculator/.gitignore
  React-Calculator/README.md
  React-Calculator/package-lock.json
  React-Calculator/package.json
  React-Calculator/public/index.html
  React-Calculator/src/App.css
  React-Calculator/src/App.js
  React-Calculator/src/index.css
  React-Calculator/src/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#40 added QR Generator Website
  QR Generator Website/index.html
  QR Generator Website/script.js
  QR Generator Website/style.css
Labels: hacktoberfest2023, hacktoberfest-accepted

#41 added a digital watch
  digital-watch/index.html
  digital-watch/script.js
  digital-watch/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#43 React Investment calculator app added
  REACT(Investment Calculator)/Readme.md
  REACT(Investment Calculator)/package-lock.json
  REACT(Investment Calculator)/package.json
  REACT(Investment Calculator)/public/favicon.ico
  REACT(Investment Calculator)/public/index.html
  REACT(Investment Calculator)/public/logo192.png
  REACT(Investment Calculator)/public/logo512.png
  REACT(Investment Calculator)/public/manifest.json
  REACT(Investment Calculator)/public/robots.txt
  REACT(Investment Calculator)/src/App.js
  REACT(Investment Calculator)/src/assets/Components/Header/Header.js
  REACT(Investment Calculator)/src/assets/Components/Header/Header.module.css
  REACT(Investment Calculator)/src/assets/Components/ResultsTable/Results.module.css
  REACT(Investment Calculator)/src/assets/Components/ResultsTable/ResultsTable.js
  REACT(Investment Calculator)/src/assets/Components/UserInput/UserInput.js
  REACT(Investment Calculator)/src/assets/Components/UserInput/UserInput.module.css
  REACT(Investment Calculator)/src/assets/investment-calculator-logo.png
  REACT(Investment Calculator)/src/index.css
  REACT(Investment Calculator)/src/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#45 image gallery slider with controls and effects added
  Image Gallery Slider/assets/p1.jpeg
  Image Gallery Slider/assets/p2.jpg
  Image Gallery Slider/assets/p3.jpg
  Image Gallery Slider/assets/p4.jpg
  Image Gallery Slider/assets/p5.jpg
  Image Gallery Slider/index.html
  Image Gallery Slider/index.js
  Image Gallery Slider/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#46 mycommit
  complex password generator/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#53 Added portfolio project
  Portfolio-project/.eslintrc.cjs
  Portfolio-project/.gitignore
  Portfolio-project/README.md
  Portfolio-project/index.html
  Portfolio-project/package-lock.json
  Portfolio-project/package.json
  Portfolio-project/postcss.config.js
  Portfolio-project/public/vite.svg
  Portfolio-project/src/App.css
  Portfolio-project/src/App.jsx
  Portfolio-project/src/assets/Home.jsx
  Portfolio-project/src/assets/astronout.png
  Portfolio-project/src/assets/astronout1.png
  Portfolio-project/src/assets/banner-bg-7d41ca4d.png
  Portfolio-project/src/assets/bannerBg.jpg
  Portfolio-project/src/assets/bg.jpg
  Portfolio-project/src/assets/contact-img.svg
  Portfolio-project/src/assets/footer-bg.png
  Portfolio-project/src/assets/meter1.svg
  Portfolio-project/src/assets/project-img1.png
  Portfolio-project/src/assets/project-img2.png
  Portfolio-project/src/assets/project-img3.png
  Portfolio-project/src/assets/react.svg
  Portfolio-project/src/assets/twitter.svg
  Portfolio-project/src/components/Contact.jsx
  Portfolio-project/src/components/Header.jsx
  Portfolio-project/src/components/Navbar.jsx
  Portfolio-project/src/components/ProjectCard.jsx
  Portfolio-project/src/components/Projects.jsx
  Portfolio-project/src/components/Skills.jsx
  Portfolio-project/src/index.css
  Portfolio-project/src/main.jsx
  Portfolio-project/src/styles.css
  Portfolio-project/tailwind.config.js
  Portfolio-project/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#51 changes created
  portfolio/index.html
  portfolio/script.js
  portfolio/smoke.mp4
  portfolio/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#60 color-switcher
  02. Color Switcher/.vscode/settings.json
  02. Color Switcher/app.js
  02. Color Switcher/index.html
  02. Color Switcher/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#59 Hangman
  Hangman/Hangman_Desc
  Hangman/index.html
  Hangman/main.js
  Hangman/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#55 A To-Do-List Project
  To-Do-List/courses.html
Labels: hacktoberfest, hacktoberfest-accepted
